FROM python:3.12-slim

WORKDIR /app

#Copy dependency files first
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir --timeout=120 -r requirements.txt

# Copy project files
COPY . .

# Start FastAPI app with Uvicorn
CMD ["python", "run_service.py"]